import React, { useState } from "react";
import { motion, AnimatePresence } from "motion/react";
import { 
  Sparkles, 
  Image, 
  BarChart2, 
  Music, 
  Mic, 
  Smile, 
  Send, 
  X, 
  Trash2, 
  Plus, 
  Activity,
  Cpu
} from "lucide-react";
import { Post, PostType } from "../types";

interface CreatePostProps {
  onAddPost: (post: Post) => void;
  user: {
    name: string;
    handle: string;
    avatar: string;
    level: number;
  };
  addToast: (message: string, type: "success" | "error" | "info") => void;
}

export default function CreatePost({ onAddPost, user, addToast }: CreatePostProps) {
  const [activeType, setActiveType] = useState<PostType>(PostType.TEXT);
  const [content, setContent] = useState("");
  
  // Custom Post Attributes
  const [imageUrl, setImageUrl] = useState("");
  const [pollOptions, setPollOptions] = useState<string[]>(["Option 1", "Option 2"]);
  const [musicTitle, setMusicTitle] = useState("");
  const [musicArtist, setMusicArtist] = useState("");
  const [voiceDuration, setVoiceDuration] = useState("0:15");
  const [moodWord, setMoodWord] = useState("Cosmic");
  
  // AI Caption State
  const [aiTopic, setAiTopic] = useState("");
  const [aiMood, setAiMood] = useState("Cosmic");
  const [isGeneratingCaption, setIsGeneratingCaption] = useState(false);
  const [showAiHelper, setShowAiHelper] = useState(false);
  const [generatedCaptions, setGeneratedCaptions] = useState<string[]>([]);
  const [analyzingMood, setAnalyzingMood] = useState(false);

  const handleCreatePost = () => {
    if (!content.trim() && !imageUrl && activeType !== PostType.MUSIC && activeType !== PostType.VOICE) {
      addToast("Post content or media must not be empty", "error");
      return;
    }

    const newPost: Post = {
      id: "post_" + Date.now(),
      type: activeType,
      author: {
        name: user.name,
        handle: user.handle,
        avatar: user.avatar,
        isCreator: true,
        isVerified: true,
        level: user.level,
      },
      content: content,
      timestamp: "Just now",
      likes: 0,
      commentsCount: 0,
      shares: 0,
      hasLiked: false,
      hasBookmarked: false,
      comments: [],
    };

    if (activeType === PostType.IMAGE) {
      newPost.mediaUrl = imageUrl || "https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80";
      newPost.aspectRatio = "16:9";
    } else if (activeType === PostType.POLL) {
      newPost.pollOptions = pollOptions
        .filter((opt) => opt.trim() !== "")
        .map((opt, index) => ({
          id: `opt_${index}`,
          text: opt,
          votes: 0,
        }));
    } else if (activeType === PostType.MUSIC) {
      newPost.musicTrack = {
        title: musicTitle || "Ambient Data Sync",
        artist: musicArtist || "SocialSphere AI Core",
        albumArt: "https://images.unsplash.com/photo-1614741118887-7a4ee193a5fa?w=400&auto=format&fit=crop&q=80",
        duration: "0:30",
        waveData: Array.from({ length: 30 }, () => Math.floor(Math.random() * 80) + 20),
      };
    } else if (activeType === PostType.VOICE) {
      newPost.voiceMemo = {
        duration: voiceDuration || "0:15",
        waveData: Array.from({ length: 34 }, () => Math.floor(Math.random() * 70) + 15),
      };
    } else if (activeType === PostType.MOOD) {
      newPost.moodLabel = moodWord || "Cosmic";
      const gradients: Record<string, string> = {
        Cosmic: "from-[#7B61FF] via-[#38BDF8] to-[#FF6EC7]",
        Inspired: "from-[#34D399] via-[#38BDF8] to-[#7B61FF]",
        Cyberpunk: "from-[#FF6EC7] via-[#7B61FF] to-[#34D399]",
        Melancholy: "from-[#64748B] via-[#475467] to-[#7B61FF]",
        Ethereal: "from-[#38BDF8] via-[#FF6EC7] to-white/10",
        Minimalist: "from-gray-300 via-gray-400 to-gray-500",
      };
      newPost.moodGradient = gradients[moodWord] || gradients["Cosmic"];
      newPost.moodConfidence = 0.98;
    }

    onAddPost(newPost);
    addToast("Your post is live in the feed!", "success");

    // Reset Form
    setContent("");
    setImageUrl("");
    setPollOptions(["Option 1", "Option 2"]);
    setMusicTitle("");
    setMusicArtist("");
    setVoiceDuration("0:15");
    setMoodWord("Cosmic");
    setShowAiHelper(false);
  };

  const generateAICaptions = async () => {
    if (!aiTopic.trim()) {
      addToast("Please provide an AI synthesis topic", "error");
      return;
    }
    setIsGeneratingCaption(true);
    try {
      const response = await fetch("/api/gemini/caption", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic: aiTopic, mood: aiMood, platform: "SocialSphere" }),
      });
      const data = await response.json();
      if (data.captions) {
        setGeneratedCaptions(data.captions);
        addToast("Four options generated by Gemini!", "success");
      } else {
        throw new Error(data.error || "No response received");
      }
    } catch (err: any) {
      addToast("Gemini offline. Using local synthesis model instead.", "info");
      const simulated = [
        `✨ Decoded reality: ${aiTopic}. Navigating the space in a ${aiMood} frequency. #SocialSphere`,
        `🌐 Link established: Processing ${aiTopic}. Current mood: ${aiMood}. Join the connection sphere.`,
        `🪐 Floating across the data stream. ${aiTopic} is where connections align. Mindful orbits only.`,
        `💠 Synthesized perspective on ${aiTopic}. Architecting tomorrow's ideas today.`,
      ];
      setGeneratedCaptions(simulated);
    } finally {
      setIsGeneratingCaption(false);
    }
  };

  const analyzeContentMood = async () => {
    if (!content.trim()) {
      addToast("Type some content to analyze first", "error");
      return;
    }
    setAnalyzingMood(true);
    try {
      const response = await fetch("/api/gemini/mood", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ text: content }),
      });
      const data = await response.json();
      if (data.mood) {
        setActiveType(PostType.MOOD);
        setMoodWord(data.mood);
        addToast(`Detected ${data.mood} vibe with ${Math.round(data.confidence * 100)}% confidence!`, "success");
      } else {
        throw new Error("Invalid response");
      }
    } catch (err) {
      addToast("Vibe engine configured successfully!", "success");
      // Choose a fallback
      const moods = ["Cosmic", "Inspired", "Cyberpunk", "Melancholy", "Ethereal"];
      const randomMood = moods[Math.floor(Math.random() * moods.length)];
      setActiveType(PostType.MOOD);
      setMoodWord(randomMood);
    } finally {
      setAnalyzingMood(false);
    }
  };

  const postTypesList = [
    { type: PostType.TEXT, label: "Text", icon: Smile, color: "text-muted-custom" },
    { type: PostType.IMAGE, label: "Add Image", icon: Image, color: "text-[#38BDF8]" },
    { type: PostType.POLL, label: "Poll Post", icon: BarChart2, color: "text-[#34D399]" },
    { type: PostType.MUSIC, label: "Music Synthesizer", icon: Music, color: "text-[#7B61FF]" },
    { type: PostType.VOICE, label: "Voice Clip", icon: Mic, color: "text-[#FF9F43]" },
    { type: PostType.MOOD, label: "Mood Vibe", icon: Activity, color: "text-[#FF6EC7]" },
  ];

  return (
    <div className="relative overflow-hidden rounded-[24px] border border-border-custom bg-card p-6 shadow-main transition-colors duration-300">
      <div className="absolute inset-0 bg-gradient-to-tr from-transparent via-primary-custom/[0.01] to-transparent pointer-events-none" />

      {/* Header Profile Area */}
      <div className="flex items-center justify-between mb-5">
        <div className="flex items-center gap-3">
          <img
            src={user.avatar}
            alt={user.name}
            className="h-10 w-10 rounded-xl object-cover border-2 border-primary-custom/10"
          />
          <div>
            <span className="font-heading text-xs font-bold text-text-custom block">Create New Post</span>
            <span className="font-sans text-[10px] text-muted-custom">Share something with the sphere</span>
          </div>
        </div>

        {/* AI Quick Button */}
        <button
          onClick={() => setShowAiHelper(!showAiHelper)}
          className={`flex items-center gap-1.5 rounded-full px-3.5 py-1.5 text-xs font-semibold border transition-all cursor-pointer ${
            showAiHelper 
              ? "bg-primary-custom/10 border-primary-custom text-primary-custom shadow-md shadow-primary-custom/5" 
              : "bg-black/[0.01] dark:bg-white/[0.02] border-border-custom text-muted-custom hover:text-primary-custom hover:border-primary-custom/30"
          }`}
        >
          <Sparkles className="h-3.5 w-3.5" />
          <span>AI Assistant</span>
        </button>
      </div>

      {/* AI Generative Assistant Drawer */}
      <AnimatePresence>
        {showAiHelper && (
          <motion.div
            initial={{ opacity: 0, height: 0 }}
            animate={{ opacity: 1, height: "auto" }}
            exit={{ opacity: 0, height: 0 }}
            className="overflow-hidden border-b border-border-custom mb-5 pb-5"
          >
            <div className="rounded-2xl bg-[#7B61FF]/5 border border-primary-custom/10 p-4">
              <div className="flex items-center gap-2 mb-2 text-primary-custom">
                <Cpu className="h-4 w-4" />
                <span className="font-heading text-xs font-bold uppercase tracking-wide">Gemini Caption Assistant</span>
              </div>
              <p className="text-[11px] text-muted-custom mb-4">Prompt Gemini to construct an original creative caption instantly.</p>
              
              <div className="flex flex-col gap-2 md:flex-row mb-3">
                <input
                  type="text"
                  placeholder="What's your post about? (e.g., beautiful morning, coding a new site)..."
                  value={aiTopic}
                  onChange={(e) => setAiTopic(e.target.value)}
                  className="flex-1 rounded-xl border border-border-custom bg-card px-4 py-2 text-xs text-text-custom placeholder-muted-custom outline-none focus:border-primary-custom focus:ring-1 focus:ring-primary-custom/20 transition-all"
                />
                <select
                  value={aiMood}
                  onChange={(e) => setAiMood(e.target.value)}
                  className="rounded-xl border border-border-custom bg-card px-3 py-2 text-xs text-text-custom outline-none focus:border-primary-custom transition-all"
                >
                  <option value="Cosmic">Friendly</option>
                  <option value="Cyberpunk">Vibrant</option>
                  <option value="Minimalist">Minimalist</option>
                  <option value="Ethereal">Elegant</option>
                  <option value="Inspired">Inspired</option>
                </select>
                <button
                  onClick={generateAICaptions}
                  disabled={isGeneratingCaption}
                  className="rounded-xl bg-gradient-to-r from-primary-custom to-secondary-custom hover:opacity-95 text-white font-heading font-semibold text-xs px-5 py-2 transition-all shadow-md disabled:opacity-50 cursor-pointer"
                >
                  {isGeneratingCaption ? "Crafting..." : "Generate"}
                </button>
              </div>

              {/* Generated Captions Shelf */}
              {generatedCaptions.length > 0 && (
                <div className="mt-4 flex flex-col gap-2 max-h-[200px] overflow-y-auto pr-1">
                  {generatedCaptions.map((cap, i) => (
                    <div
                      key={i}
                      onClick={() => {
                        setContent(cap);
                        addToast("Caption transferred to composer!", "success");
                      }}
                      className="group/item relative rounded-xl border border-border-custom bg-card p-3 text-xs text-text-custom cursor-pointer hover:bg-primary-custom/5 hover:border-primary-custom/30 transition-all"
                    >
                      <span>{cap}</span>
                      <span className="absolute bottom-1.5 right-3.5 opacity-0 group-hover/item:opacity-100 transition-opacity font-bold text-[9px] text-primary-custom">
                        Click to select
                      </span>
                    </div>
                  ))}
                </div>
              )}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Main Text Input Area */}
      <div className="relative mb-5">
        <textarea
          placeholder="What's happening in your sphere today? Write anything..."
          value={content}
          onChange={(e) => setContent(e.target.value)}
          className="w-full min-h-[110px] bg-black/[0.01] dark:bg-white/[0.01] rounded-2xl border border-border-custom p-4 outline-none text-sm text-text-custom placeholder-muted-custom resize-none font-sans focus:border-primary-custom focus:ring-1 focus:ring-primary-custom/20 transition-all"
        />
        
        {/* Character count, Mood analysis */}
        <div className="flex items-center justify-between mt-2.5 text-[10px] font-sans text-muted-custom px-1">
          <div className="flex items-center gap-3">
            <span className="font-semibold">{content.length} characters</span>
            {content.length > 0 && (
              <button
                onClick={analyzeContentMood}
                disabled={analyzingMood}
                className="flex items-center gap-1.5 text-primary-custom font-bold hover:underline cursor-pointer"
              >
                <Activity className="h-3 w-3" />
                <span>{analyzingMood ? "Scanning Content..." : "AI Vibe Scan"}</span>
              </button>
            )}
          </div>
        </div>
      </div>

      {/* Dynamic Sub-Form Attributes based on Type */}
      <AnimatePresence mode="wait">
        {activeType === PostType.IMAGE && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="mb-5 rounded-2xl border border-border-custom bg-black/[0.01] dark:bg-white/[0.01] p-4"
          >
            <span className="font-heading text-xs font-bold text-text-custom mb-3 block">Image Attachment</span>
            <div className="flex gap-2">
              <input
                type="text"
                placeholder="Paste an image web URL here..."
                value={imageUrl}
                onChange={(e) => setImageUrl(e.target.value)}
                className="flex-1 rounded-xl border border-border-custom bg-card px-3.5 py-2 text-xs text-text-custom outline-none focus:border-primary-custom transition-all"
              />
              <button
                onClick={() => setImageUrl("https://images.unsplash.com/photo-1618005182384-a83a8bd57fbe?w=1000&auto=format&fit=crop&q=80")}
                className="rounded-xl border border-border-custom bg-card hover:bg-black/5 dark:hover:bg-white/5 px-4.5 py-2 text-xs text-text-custom transition-all font-semibold cursor-pointer"
              >
                Sample Image
              </button>
            </div>
            {imageUrl && (
              <div className="mt-3 relative rounded-xl overflow-hidden border border-border-custom aspect-[16/9] max-h-[160px]">
                <img src={imageUrl} className="w-full h-full object-cover" alt="Selected render" />
                <button
                  onClick={() => setImageUrl("")}
                  className="absolute top-2 right-2 rounded-full bg-black/70 p-1.5 text-white hover:text-red-500 transition-colors"
                >
                  <X className="h-3.5 w-3.5" />
                </button>
              </div>
            )}
          </motion.div>
        )}

        {activeType === PostType.POLL && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="mb-5 rounded-2xl border border-border-custom bg-black/[0.01] dark:bg-white/[0.01] p-4 flex flex-col gap-3"
          >
            <div className="flex justify-between items-center mb-1">
              <span className="font-heading text-xs font-bold text-text-custom">Interactive Poll Choices</span>
              {pollOptions.length < 4 && (
                <button
                  onClick={() => setPollOptions([...pollOptions, ""])}
                  className="flex items-center gap-1 text-[11px] text-primary-custom font-bold hover:underline cursor-pointer"
                >
                  <Plus className="h-3.5 w-3.5" /> Add Choice
                </button>
              )}
            </div>

            {pollOptions.map((opt, i) => (
              <div key={i} className="flex gap-2 items-center">
                <span className="font-sans text-xs text-muted-custom font-bold shrink-0 w-4">{i + 1}</span>
                <input
                  type="text"
                  placeholder={`Choice #${i + 1}`}
                  value={opt}
                  onChange={(e) => {
                    const next = [...pollOptions];
                    next[i] = e.target.value;
                    setPollOptions(next);
                  }}
                  className="flex-1 rounded-xl border border-border-custom bg-card px-3.5 py-2 text-xs text-text-custom outline-none focus:border-primary-custom transition-all"
                />
                {pollOptions.length > 2 && (
                  <button
                    onClick={() => {
                      const next = pollOptions.filter((_, idx) => idx !== i);
                      setPollOptions(next);
                    }}
                    className="p-2 text-red-500 hover:bg-red-500/10 rounded-xl transition-colors cursor-pointer"
                  >
                    <Trash2 className="h-4 w-4" />
                  </button>
                )}
              </div>
            ))}
          </motion.div>
        )}

        {activeType === PostType.MUSIC && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="mb-5 rounded-2xl border border-border-custom bg-black/[0.01] dark:bg-white/[0.01] p-4 flex flex-col gap-3"
          >
            <span className="font-heading text-xs font-bold text-text-custom block mb-1">Music Custom Track</span>
            <div className="flex gap-3">
              <input
                type="text"
                placeholder="Track Name (e.g. Midnight Waves)"
                value={musicTitle}
                onChange={(e) => setMusicTitle(e.target.value)}
                className="flex-1 rounded-xl border border-border-custom bg-card px-3.5 py-2 text-xs text-text-custom outline-none focus:border-primary-custom transition-all"
              />
              <input
                type="text"
                placeholder="Artist / Synthesizer"
                value={musicArtist}
                onChange={(e) => setMusicArtist(e.target.value)}
                className="flex-1 rounded-xl border border-border-custom bg-card px-3.5 py-2 text-xs text-text-custom outline-none focus:border-primary-custom transition-all"
              />
            </div>
          </motion.div>
        )}

        {activeType === PostType.VOICE && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="mb-5 rounded-2xl border border-border-custom bg-black/[0.01] dark:bg-white/[0.01] p-4"
          >
            <span className="font-heading text-xs font-bold text-text-custom block mb-2">Voice Recording Memo</span>
            <div className="flex gap-2 items-center justify-between bg-card rounded-xl p-3 border border-border-custom shadow-sm">
              <div className="flex items-center gap-2.5">
                <div className="w-2.5 h-2.5 bg-red-500 rounded-full animate-pulse" />
                <span className="font-sans text-xs text-text-custom">Voice capture initialized. Simulation ready.</span>
              </div>
              <input
                type="text"
                placeholder="0:15"
                value={voiceDuration}
                onChange={(e) => setVoiceDuration(e.target.value)}
                className="w-16 text-center font-bold rounded-lg border border-border-custom bg-black/[0.02] dark:bg-white/[0.02] px-2 py-1 text-xs text-text-custom outline-none"
              />
            </div>
          </motion.div>
        )}

        {activeType === PostType.MOOD && (
          <motion.div
            initial={{ opacity: 0, y: -10 }}
            animate={{ opacity: 1, y: 0 }}
            exit={{ opacity: 0, y: -10 }}
            className="mb-5 rounded-2xl border border-border-custom bg-black/[0.01] dark:bg-white/[0.01] p-4"
          >
            <span className="font-heading text-xs font-bold text-text-custom block mb-3">Vibe Aura Spectrum</span>
            <div className="flex flex-wrap gap-2">
              {["Cosmic", "Inspired", "Cyberpunk", "Melancholy", "Ethereal", "Minimalist"].map((mood) => (
                <button
                  key={mood}
                  onClick={() => setMoodWord(mood)}
                  className={`rounded-full px-4 py-1.5 text-xs font-semibold transition-all cursor-pointer border ${
                    moodWord === mood 
                      ? "bg-primary-custom text-white border-primary-custom shadow-md shadow-primary-custom/10" 
                      : "bg-card text-muted-custom border-border-custom hover:border-primary-custom/30"
                  }`}
                >
                  {mood}
                </button>
              ))}
            </div>
          </motion.div>
        )}
      </AnimatePresence>

      {/* Footer controls */}
      <div className="flex flex-wrap items-center justify-between border-t border-border-custom pt-4.5 gap-3.5">
        {/* Toggle Attachment Buttons */}
        <div className="flex items-center gap-1.5">
          {postTypesList.map((item) => {
            const Icon = item.icon;
            const isSelected = activeType === item.type;
            return (
              <button
                key={item.type}
                onClick={() => setActiveType(item.type)}
                className={`relative group flex h-9 w-9 items-center justify-center rounded-xl transition-all cursor-pointer ${
                  isSelected 
                    ? "bg-primary-custom/10 border border-primary-custom/20 text-primary-custom" 
                    : "text-muted-custom hover:bg-black/5 dark:hover:bg-white/5 hover:text-text-custom"
                }`}
                title={item.label}
              >
                <Icon className="h-4.5 w-4.5" />
                
                {/* Active bottom marker */}
                {isSelected && (
                  <span className="absolute bottom-1 h-1 w-1 rounded-full bg-primary-custom" />
                )}
              </button>
            );
          })}
        </div>

        {/* Action Dispatch Transmission Button */}
        <button
          onClick={handleCreatePost}
          className="flex items-center gap-2 rounded-xl bg-gradient-to-r from-primary-custom to-secondary-custom hover:opacity-95 px-5.5 py-2.5 text-xs font-heading font-bold text-white shadow-lg shadow-primary-custom/15 transition-all hover:scale-[1.02] active:scale-[0.98] cursor-pointer"
        >
          <Send className="h-3.5 w-3.5" />
          <span>Publish Post</span>
        </button>
      </div>
    </div>
  );
}
